name: IsMyMicOn
options:
  bundleIdPrefix: com.yansenzhou
  deploymentTarget:
    macOS: "11.0"
targets:
  IsMyMicOn:
    type: application
    platform: macOS
    sources:
      - Sources
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: IsMyMicOn
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        LSUIElement: true
        NSMicrophoneUsageDescription: Microphone access is used to show the input level meter.
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yansenzhou.ismymicon
        MARKETING_VERSION: 0.1.1
        CURRENT_PROJECT_VERSION: 2
